#!/bin/bash

ANDROID_TOOLCHAIN=clang ;
ANDROID_STL=c++_static ;
ANDROID_ARCHS="armeabi-v7a arm64-v8a"; # "x86 x86_64 armeabi-v7a arm64-v8a";
ANDROID_CPP_FEATURES="rtti exceptions" ;

ANDROID_COMPILE_SDK_VERSION=28;
ANDROID_MIN_SDK_VERSION=21;
ANDROID_TARGET_SDK_VERSION=28;
