############################################################
#             Source: http://libuv.org/                    #
############################################################

set (ATFRAME_THIRD_PARTY_LIBUV_VERSION "1.27.0")
set (ATFRAME_THIRD_PARTY_LIBUV_PKG_DIR "${ATFRAME_THIRD_PARTY_TARGET_OPENSSL_BUILD_DIR}/source")
set (ATFRAME_THIRD_PARTY_LIBUV_PKG_PATH"${ATFRAME_THIRD_PARTY_LIBUV_PKG_DIR}/libuv-v${ATFRAME_THIRD_PARTY_LIBUV_VERSION}.tar.gz")
set (ATFRAME_THIRD_PARTY_LIBUV_SRC_DIR "${ATFRAME_THIRD_PARTY_LIBUV_PKG_DIR}/libuv-v${ATFRAME_THIRD_PARTY_LIBUV_VERSION}")

if (NOT EXISTS ${ATFRAME_THIRD_PARTY_LIBUV_PKG_DIR})
    file (MAKE_DIRECTORY ${ATFRAME_THIRD_PARTY_LIBUV_PKG_DIR})
endif ()

if (NOT EXISTS ${ATFRAME_THIRD_PARTY_LIBUV_SRC_DIR})
    if (NOT EXISTS ${ATFRAME_THIRD_PARTY_LIBUV_PKG_PATH})
        file(DOWNLOAD "https://dist.libuv.org/dist/v${ATFRAME_THIRD_PARTY_LIBUV_VERSION}/libuv-v${ATFRAME_THIRD_PARTY_LIBUV_VERSION}.tar.gz" ${ATFRAME_THIRD_PARTY_LIBUV_PKG_PATH} SHOW_PROGRESS)
    endif ()

    execute_process(
        COMMAND ${CMAKE_COMMAND} -E tar xvf ${ATFRAME_THIRD_PARTY_LIBUV_PKG_PATH}
        WORKING_DIRECTORY ${ATFRAME_THIRD_PARTY_LIBUV_PKG_DIR}
    )
endif ()

if (NOT EXISTS ${ATFRAME_THIRD_PARTY_LIBUV_SRC_DIR})
    message(FATAL_ERROR "${ATFRAME_THIRD_PARTY_LIBUV_SRC_DIR} not found.")
endif ()

# standard cmake project
ATPBTargetBuildThirdPartyByCMake(${ATFRAME_THIRD_PARTY_LIBUV_SRC_DIR} 
    "-DBUILD_SHARED_LIBS=NO" "-DBUILD_TESTING=OFF"
)
